# Generated by Django 4.2 on 2023-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_name", models.TextField()),
                ("f_name", models.TextField()),
                ("l_name", models.TextField()),
                ("e_mail", models.EmailField(max_length=254, unique=True)),
                ("pass_1", models.TextField(max_length=128)),
                ("pass_2", models.TextField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name="Login",
        ),
    ]
