# Generated by Django 4.2 on 2023-05-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_newuser_delete_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newuser",
            old_name="e_mail",
            new_name="u_email",
        ),
    ]
