# Generated by Django 4.2 on 2023-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_rename_e_mail_newuser_u_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="u_email",
            field=models.TextField(max_length=128),
        ),
    ]
