# Generated by Django 4.1.7 on 2023-06-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_alter_newuser_u_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newuser",
        ),
    ]
