# Generated by Django 4.1.7 on 2023-06-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_newuser_delete_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newuser",
        ),
    ]
